/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pengaturan;

import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author HP
 */
public class sandi extends javax.swing.JFrame {

    String sandiLama;
    String sandiBaru;
    String konfirmasiSandi;
    
    /** Creates new form sandi */
    public sandi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        koneksi();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        utamaPanel = new javax.swing.JPanel();
        judulPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        sandiPanel = new javax.swing.JPanel();
        sandilamaLabel = new javax.swing.JLabel();
        sandibaruLabel = new javax.swing.JLabel();
        konfirmasisandiLabel = new javax.swing.JLabel();
        sandilamaText = new javax.swing.JTextField();
        sandibaruText = new javax.swing.JTextField();
        konfirmasisandiText = new javax.swing.JTextField();
        batalButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        utamaPanel.setBackground(new java.awt.Color(10, 4, 60));

        judulPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulLabel.setBackground(new java.awt.Color(255, 255, 255));
        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("UBAH SANDI");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sandiPanel.setBackground(new java.awt.Color(128, 255, 219));

        sandilamaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sandilamaLabel.setText("Sandi Lama");

        sandibaruLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sandibaruLabel.setText("Sandi Baru");

        konfirmasisandiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        konfirmasisandiLabel.setText("Konfirmasi Sandi");

        sandilamaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandilamaTextActionPerformed(evt);
            }
        });
        sandilamaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sandilamaTextKeyTyped(evt);
            }
        });

        sandibaruText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sandibaruTextKeyTyped(evt);
            }
        });

        konfirmasisandiText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                konfirmasisandiTextKeyTyped(evt);
            }
        });

        batalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        batalButton.setText("BATAL");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        ubahButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ubahButton.setText("UBAH");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sandiPanelLayout = new javax.swing.GroupLayout(sandiPanel);
        sandiPanel.setLayout(sandiPanelLayout);
        sandiPanelLayout.setHorizontalGroup(
            sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sandibaruLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sandilamaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(konfirmasisandiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sandiPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ubahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalButton))
                    .addComponent(sandilamaText)
                    .addComponent(sandibaruText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(konfirmasisandiText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        sandiPanelLayout.setVerticalGroup(
            sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sandilamaText, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(sandilamaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sandibaruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandibaruText, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konfirmasisandiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konfirmasisandiText, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sandiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout utamaPanelLayout = new javax.swing.GroupLayout(utamaPanel);
        utamaPanel.setLayout(utamaPanelLayout);
        utamaPanelLayout.setHorizontalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sandiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utamaPanelLayout.setVerticalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sandiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pengaturan().setVisible(true);
    }//GEN-LAST:event_batalButtonActionPerformed

    private void sandilamaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sandilamaTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((Character.isDigit(c)) || (Character.isAlphabetic(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
            
        }else{
            JOptionPane.showMessageDialog(this, "Input hanya dapat angka dan huruf");
            evt.consume();
        }
    }//GEN-LAST:event_sandilamaTextKeyTyped

    private void sandibaruTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sandibaruTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((Character.isDigit(c)) || (Character.isAlphabetic(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
            
        }else{
            JOptionPane.showMessageDialog(this, "Input hanya dapat angka dan huruf");
            evt.consume();
        }
    }//GEN-LAST:event_sandibaruTextKeyTyped

    private void konfirmasisandiTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konfirmasisandiTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((Character.isDigit(c)) || (Character.isAlphabetic(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
            
        }else{
            JOptionPane.showMessageDialog(this, "Input hanya dapat angka dan huruf");
            evt.consume();
        }
    }//GEN-LAST:event_konfirmasisandiTextKeyTyped

    private void sandilamaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandilamaTextActionPerformed
           
    }//GEN-LAST:event_sandilamaTextActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        koneksi();
        String sandiLama1 = sandilamaText.getText();
        sandiBaru = sandibaruText.getText();
        konfirmasiSandi = konfirmasisandiText.getText();
        
        if(!sandiLama.equals(sandiLama1)){
            JOptionPane.showMessageDialog(null, "Sandi lama yang dimasukkan salah","Peringatan", JOptionPane.ERROR_MESSAGE);
        }else if(!sandiBaru.equals(konfirmasiSandi)){
            JOptionPane.showMessageDialog(null, "Sandi baru tidak sesuai dengan konfirmasi sandi","Peringatan", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/db_kasirrestoranswing", "root", "");
                PreparedStatement ps = cn.prepareStatement("update tb_sandi set sandi=? where id_sandi=?");
                ps.setString(1, sandiBaru);
                ps.setInt(2, 1);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Ubah sandi berhasil","Pesan", JOptionPane.OK_OPTION);
                this.setVisible(false);
                new pengaturan().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(sandi.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Koneksi Ke Database MySql Tidak Berhasil","Peringatan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ubahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sandi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JLabel konfirmasisandiLabel;
    private javax.swing.JTextField konfirmasisandiText;
    private javax.swing.JPanel sandiPanel;
    private javax.swing.JLabel sandibaruLabel;
    private javax.swing.JTextField sandibaruText;
    private javax.swing.JLabel sandilamaLabel;
    private javax.swing.JTextField sandilamaText;
    private javax.swing.JButton ubahButton;
    private javax.swing.JPanel utamaPanel;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/db_kasirrestoranswing", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM tb_sandi");
            rs.next();
            sandiLama = rs.getString(2);
        } catch (Exception ex) {
            Logger.getLogger(sandi.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Koneksi Ke Database MySql Tidak Berhasil","Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }

}
